name: 'UbiDoc'
description: 'Ubiquitous Language HTML Generator'
author: 'Ryo Muramatsu'
branding:
  icon: 'book'
  color: 'blue'

inputs:
  output:
    description: '生成された HTML の出力先パス（リポジトリ内のパスを指定）'
    required: false
    default: 'sample/generated.html'
  repo:
    description: 'GitHubリポジトリ (owner/repo)'
    required: false
    default: 'owner/repo'
  branch:
    description: 'ブランチ名 (例: main)'
    required: false
    default: 'main'

runs:
  using: 'docker'
  image: 'Dockerfile'

  env:
    GITHUB_REPOSITORY: ${{ inputs.repo }}
    GITHUB_REF_NAME: ${{ inputs.branch }}

  args:
    - '--input'
    - "."
    - '--output'
    - ${{ inputs.output }}
