name: 'UbiDoc'
description: 'Ubiquitous Language HTML Generator'
author: 'Ryo Muramatsu'
branding:
  icon: 'book'
  color: 'blue'

inputs:
  output_dir:
    description: 'output doc directory path'
    required: false
    default: 'docs/ubi-doc'
  repo:
    description: 'GitHub repository (ex: owner/repo)'
    required: false
    default: 'owner/repo'
  branch:
    description: 'branch name (ex: main)'
    required: false
    default: 'main'

runs:
  using: 'docker'
  image: 'Dockerfile'

  env:
    GITHUB_REPOSITORY: ${{ inputs.repo }}
    GITHUB_REF_NAME: ${{ inputs.branch }}

  args:
    - '--input'
    - "."
    - '--output'
    - ${{ inputs.output_dir }}
