name: Test Ubiquitous Generator Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ubiquitous Generator Action
        uses: ./
        with:
          output: 'sample/generated.html'

      - name: Show generated HTML
        run: cat sample/generated.html || echo "No generated file found."
