name: Test Ubi Doc Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest

    # GITHUB_TOKEN を使ってPull Requestを作成・Pushするための権限を設定
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ubi Doc Action
        uses: ./
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        with:
          output: 'sample/generated.html'

      - name: Show generated HTML
        run: cat sample/generated.html || echo "No generated file found."

      - name: Create Pull Request (via gh CLI)
        # GH CLIはデフォルトで GH_TOKEN 環境変数を参照するため、GITHUB_TOKEN を割り当てます
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. Git のユーザー設定
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 2. ユニークなブランチ名を作成: auto-generated-html/<run_id>
          BRANCH_NAME="auto-generated-html/${{ github.run_id }}"
          git checkout -b "$BRANCH_NAME"

          # 3. 変更をコミット
          git add sample/generated.html
          git commit -m $'chore: Add generated HTML\n\nAuto-commit by GitHub Actions.'

          # 4. ブランチをリモートにPush
          git push origin "$BRANCH_NAME"

          # 5. Pull Requestを作成
          gh pr create \
            --base main \
            --head "$BRANCH_NAME" \
            --title "Add generated HTML via GitHub Actions" \
            --body "このPull Requestでは、最新のHTMLファイルを自動生成・追加しました。"
