name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: build
        run: cargo build --verbose

      - name: execute tests
        run: cargo test --verbose
